trigger: none

variables:
  AuthenticodeSignType: '400'
  BuildConfiguration: 'Release'
  NuGetPackagePath: '$(System.ArtifactsDirectory)/NuGetRelease'
  PackageRoot: '$(System.ArtifactsDirectory)/Packages'



stages:
- stage: Build
  displayName: Build PowerShellGet
  dependsOn: []
  jobs:
  - job: BuildWin
    pool:
      vmImage: vs2017-win2016
    displayName: Windows
    strategy:
      matrix:
        x64:
          ARCHITECTURE: x64
        x86:
          ARCHITECTURE: x86
        x64ARM:
          ARCHITECTURE: x64_arm
        x64ARM64:
          ARCHITECTURE: x64_arm64
    steps:
    - template: windows-build.yml

  - job: SignWin
    pool: Package ES Standard Build
    displayName: Sign Windows
    dependsOn: BuildWin
    strategy:
      matrix:
        x64:
          ARCHITECTURE: x64
        x86:
          ARCHITECTURE: x86
        x64ARM:
          ARCHITECTURE: x64_arm
        x64ARM64:
          ARCHITECTURE: x64_arm64
    steps:
    - template: windows-sign.yml




  - job: BuildNuGetPkg
    displayName: Build NuGet Package
    dependsOn:
    - SignWin
    - BuildLinux
    - BuildMac
    pool: Package ES Standard Build

    steps:
    - template: nuget.yml



- template: publish.yml
  parameters:
    stageName: AzArtifactsFeed
    environmentName: PSNativeAzArtifactApproval
    feedCredential: AzArtifactsFeed



- template: publish.yml
  parameters:
    stageName: NuGet
    environmentName: PSNativeNuGetApproval
    feedCredential: PowerShellNuGetOrgPush
